[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solar = "WmiUzNXC9NadW5NiEaUUCHj8MSbcRyusELEBxemrryf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/vaithee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
