[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solar = "DL79DkQFevrJrjVFhi8W2sSgaxizW84vwxviTggQThvY"
[programs.localnet]
solar = "8zmYTinF3yjHpQgqo7jhhcATj7GDvS2v1iZGZns1JABp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/vaithee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
